#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

[[ " help env-gen:help " == *" $1 "* ]] || exit "$DOKKU_NOT_IMPLEMENTED_EXIT"

source "$PLUGIN_AVAILABLE_PATH/env-gen/help-functions"

case "$1" in
  help | env-gen:help)
    cmd-env-gen-help "$@"
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac