#!/usr/bin/env bash

source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"
source "$PLUGIN_AVAILABLE_PATH/env-gen/internal-functions"

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

trigger-env-gen-post-extract(){
   declare desc="copies environment variables into an env file"
   declare trigger="post-extract"
   declare APP="$1" TMP_WORK_DIR="$2"

   verify_app_name "$APP"

   if [[ "$(fn-env-gen-enabled "$APP")" != "true" ]]; then
      return
   fi

   pushd "$TMP_WORK_DIR" >/dev/null

   if [[ -f ".env" ]]; then
      return
   fi

   dokku_log_info1 "Generating .env file for $APP..."

   touch ".env"

   config_export app "$APP" --format envfile >>".env"

   cat ".env"

   popd &>/dev/null

   dokku_log_verbose ".env file for $APP generated successfully"
}

trigger-env-gen-post-extract "$@"